version: 2
jobs:
  build:
    docker:
      # Closest available image to 6.5.0 which is the version of Node.js on Azure functions.
      # We use the image with browsers included to be able to use Chromium.
      # See https://hub.docker.com/r/circleci/node/tags/
      # See https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#node-version-and-package-management
      # See https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html
      - image: circleci/node:6.12-browsers
    steps:
      - checkout
      - restore_cache:
          key: root-node-modules-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: root-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run prettier --list-different
      - run: yarn run eslint
      - run:
          command: yarn run test --coverage --testResultsProcessor=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: reports/junit.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
          destination: coverage
      - run:
          command: yarn run bundle
          working_directory: packages/browser-based-pdf-export-lambda
      - run:
          command: yarn run zip
          working_directory: packages/browser-based-pdf-export-lambda
      - store_artifacts:
          path: packages/browser-based-pdf-export-lambda/dist.zip
          destination: browser-based-pdf-export-lambda.zip
